"""create_car_table

Revision ID: 6fc3e9e1b7fb
Revises: 0002_add_auth_tables
Create Date: 2025-11-20 18:38:57.271394

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003_create_car_table'
down_revision: Union[str, None] = '0002_add_auth_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_make'), 'car', ['make'], unique=False)
    op.create_index(op.f('ix_car_model'), 'car', ['model'], unique=False)
    op.create_index(op.f('ix_car_year'), 'car', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_year'), table_name='car')
    op.drop_index(op.f('ix_car_model'), table_name='car')
    op.drop_index(op.f('ix_car_make'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
