"""create_book_table

Revision ID: aa8369d40495
Revises: 6fc3e9e1b7fb
Create Date: 2025-11-22 10:17:28.247718

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa8369d40495'
down_revision: Union[str, None] = '6fc3e9e1b7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists to avoid errors on retry
    bind = op.get_bind()
    insp = sa.Inspector.from_engine(bind.engine)
    if 'book' not in insp.get_table_names():
        op.create_table('book',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('pages', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
        op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
        op.create_index(op.f('ix_book_year'), 'book', ['year'], unique=False)
    # SQLite doesn't support ALTER COLUMN to change data types.
    # Skip this alter for SQLite as TEXT and AutoString are functionally equivalent
    if bind.engine.name != 'sqlite':
        op.alter_column('contact', 'message',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=False)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_book_year'), table_name='book')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
